webproject/webproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webprojectapp.urls')),
]

webproject/webprojectapp/urls.py
from django.urls import path
from webprojectapp import views

urlpatterns = [
    # Sections.
    path('', views.main),
    path('home/', views.home, name="homepage"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logut_user, name="logout"),
    path('register/apartment/', views.FormApartmentView.register_form, name="register_apartment"),
    path('details_apartment/<int:id>', views.detailsApartment, name="details"),
    # Actions
    path('update/apartment/<int:id>/state/<slug:state>', views.ApartamentActions.updateApartamentState)
]

webproject/webprojectapp/models.py
from django.db import models

# Create your models here.

""" SQL Process.
1. Migrate model clasess:
    python3 manage.py makemigrations

2. Create SQL code:
    python3 manage.py sqlmigrate webprojectapp {n_migration}

3. Save tables:
    python3 manage.py migrate
"""

class Apartment(models.Model):

    stateOptions = (
        ('available', 'Disponible'),
        ('unavailable', 'Ocupado'),
    )

    id = models.BigAutoField(primary_key=True)
    matricula_inmueble = models.TextField(unique=True)
    ciudad = models.TextField()
    direccion = models.CharField(max_length=50)
    nombre_unidad_residencial = models.CharField(max_length=250)
    numero_piso = models.IntegerField()
    numero_apartamento = models.IntegerField()
    numero_habitaciones = models.IntegerField()
    numero_banos = models.IntegerField()
    precio_dia = models.TextField()
    estado = models.CharField(
        max_length = 20,
        choices = stateOptions,
        default = 'available'
    )

    def get_all():
        return Apartment.objects.all()

    def get_all_availables():
        return len(Apartment.objects.filter(estado = 'available'))

    def get_all_unavailables():
        return len(Apartment.objects.filter(estado = 'unavailable'))

    def get_by_id(apartament_id):
        apartament = Apartment.objects.filter(id = apartament_id)
        if apartament:
            return apartament
        
        return False

    def update_state(apartament, state):       
        return apartament.update(estado = state)

webproject/webprojectapp/forms.py
from dataclasses import fields
from django import forms

from webprojectapp.models import Apartment

class ApartmentForm(forms.ModelForm):
    error_messages = {
        "invalid" : "El valor debe ser un número entero"
    }

    direccion = forms.CharField(
        label = "Dirección"
    )
    ciudad = forms.CharField()
    matricula_inmueble = forms.CharField(
        label = "Matrícula del inmueble"
    )
    numero_piso = forms.CharField(
        label = "Número de piso",
        error_messages = error_messages
    )
    numero_apartamento = forms.CharField(
        label = "Número de apartamento",
        error_messages = error_messages
    )
    numero_habitaciones = forms.CharField(
        label = "Número de habitaciones",
        error_messages = error_messages
    )
    numero_banos = forms.CharField(
        label = "Número de baños",
        error_messages = error_messages
    )
    precio_dia = forms.CharField(
        label = "Precio / día",
        error_messages = error_messages
    )

    class Meta:
        model = Apartment
        fields = [
            'direccion',
            'ciudad',
            'matricula_inmueble',
            'numero_piso',
            'numero_apartamento',
            'numero_habitaciones',
            'numero_banos',
            'precio_dia',
        ]
        

webproject/webprojectapp/views.py
from django.http import HttpRequest, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from webprojectapp.forms import ApartmentForm
from webprojectapp.models import Apartment

# Create your views here.

def main(request):
    return redirect('homepage')

def login_user(request):
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)

        if user is not None:
            login(request, user)
            return redirect('homepage')
        else:
            messages.error(request, "Usuario o contraseña incorrectos")
    
    return render(request, "auth/login.html")

@login_required(login_url="login")
def home(request):
    context = {
        'appartments': Apartment.get_all(),
        'availables': Apartment.get_all_availables(),
        'unavailables': Apartment.get_all_unavailables(),
    }
    return render(request, "home.html", context)

@login_required(login_url="login")
def logut_user(request):
    logout(request)
    return redirect('login')

@login_required(login_url="login")
def detailsApartment(request, id):
    apartment = get_object_or_404(Apartment, pk=id)
    return render(request, 'apt-details.html', {'apartment': apartment})

class FormApartmentView(HttpRequest):

    @login_required(login_url="login")
    def register_form(request):

        apartment = ApartmentForm()
        
        if request.method == 'POST':
            apartment = ApartmentForm(request.POST)
            
            if apartment.is_valid():
                apartment.save()
                messages.success(request, 'Se registró el apartamento correctamente.')
                return redirect('homepage')
        
        return render(request, "apt-register.html", {"form": apartment})

class ApartamentActions(HttpRequest):

    @login_required(login_url="login")
    def updateApartamentState(request, id, state):
        # Validations.
        if state not in ['available', 'unavailable']:
            return JsonResponse({
                "status" : 0,
                "message": "Bad request",
            })

        apartament = Apartment.get_by_id(id)
        if apartament == False:
            return JsonResponse({
                "status" : 0,
                "message": "Apartament was not found",
            })

        # Update state.
        if Apartment.update_state(apartament, state):
            return JsonResponse({
                "status" : 1,
                "message": "Apartament updated successfully",
            })
        else:
            return JsonResponse({
                "status" : 0,
                "message": "Internal Error!",
            })

webproject/webprojectapp/templates/apt-details.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles Apartamento</title>
    <link rel="stylesheet" href="{% static 'css/apt-details.css' %}">
</head>
<body>
    <header>
        <h1></h1>
        <a href=""><img class="logo" src="https://cdn-icons-png.flaticon.com/512/149/149071.png" alt=""></a>
    </header>
    <main>
        <div class="box1">
            <div class="form-container">
                <label class="navegation-menu">Menú de Navegación</label>
                <div>
                    <a href="{% url 'homepage' %}"><button class="submit">Inicio</button></a>
                </div>
                <div>
                    <a href="{% url 'register_apartment' %}"><button class="submit">Registrar Apartamento</button></a>
                </div>
            </div>
        </div>
        <section class="main-section">
                <h2>Detalles del apartamento</h2>
                <div class="user-details">
                    <label for="direccion">Dirección:</label>
                    <div>{{ apartment.direccion }}</div>

                    <label>Ciudad:</label>
                    <div>{{ apartment.ciudad }}</div>

                    <label>Matrícula del inmueble:</label>
                    <div>{{ apartment.matricula_inmueble }}</div>

                    <label>Número de piso:</label>
                    <div>{{ apartment.numero_piso }}</div>

                    <label>Número de apartamento:</label>
                    <div>{{ apartment.numero_apartamento }}</div>

                    <label>Número de habitaciones:</label>
                    <div>{{ apartment.numero_habitaciones}}</div>

                    <label>Número de baños:</label>
                    <div>{{ apartment.numero_baños }}</div>

                    <label>Precio / día</label>
                    <div>{{ apartment.precio_dia }}</div>
                </div>
        </section>
    </main>
    <footer><a href="{% url 'logout' %}"><button>Log Out</button></a></footer>
</body>
</html>

webproject/webprojectapp/templates/apt-register.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar Apartamento</title>
    <link rel="stylesheet" href="{% static 'css/apt-register.css' %}">
</head>
<body>
    <header>
        <h1></h1>
        <a href=""><img class="logo" src="https://cdn-icons-png.flaticon.com/512/149/149071.png" alt=""></a>
    </header>
    <main>
        <div class="box1">
            <div class="form-container">
                <label class="navegation-menu">Menú de Navegación</label>
                <div>
                    <a href="{% url 'homepage' %}"><button class="submit">Inicio</button></a>
                </div>
                <div>
                    <a href="{% url 'register_apartment' %}"><button class="submit">Registrar Apartamento</button></a>
                </div>
            </div>
        </div>
        <section class="main-section">
            <form action="{% url 'register_apartment' %}" method="post">
                {% csrf_token %}
                <h2>Detalles del apartamento</h2>                
                <div class="user-details">
    
                    {% for field in form %}
                        <div class="info">
                            {{field.label_tag}}
                            {{field}}
                            {% for error in field.errors %}
                                <span class="error-message">{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% endfor %}

                    <input type="submit" value="Save">
                </div>
            </form>
        </section>
    </main>
    <footer><a href="{% url 'logout' %}"><button>Log Out</button></a></footer>
</body>
</html>

webproject/webprojectapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
    <header>
        <h1></h1>
        <a href=""><img class="logo" src="https://cdn-icons-png.flaticon.com/512/149/149071.png" alt=""></a>
    </header>
    <main>
        <div class="box1">
            <div class="form-container">
                <label class="navegation-menu">Menú de Navegación</label>
                <div>
                    <a href="{% url 'homepage' %}"><button class="submit">Inicio</button></a>
                </div>
                <div>
                    <a href="{% url 'register_apartment' %}"><button class="submit">Registrar Apartamento</button></a>
                </div>
            </div>
        </div>
        <div class="main-section">
            <div class="sections">
                <section>
                    <div class="div-logitos"><img class="logitos" src="https://casa-web.com.ar/wp-content/uploads/2018/11/logo-casa-web.jpg" alt="">
                    </div>
                    <div>
                        <div class="contenido">{{ availables }}</div>
                        <div>Disponibles</div>
                    </div>
                </section>
                <section>
                    <div class="div-logitos"><img class="logitos" src="https://casa-web.com.ar/wp-content/uploads/2018/11/logo-casa-web.jpg" alt=""></div>
                    <div>
                        <div class="contenido">{{ unavailables }}</div>
                        <div>Ocupados</div>
                    </div>
                </section>
            </div>
            <div class="table">
                <table>
                    <tr>
                        <th>Apartamento</th>
                        <th>Dirección</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                    {% if appartments %}
                        {% for appartment in appartments %}
                            <tr>
                                <td>{{ appartment.matricula_inmueble }}</td>
                                <td>{{ appartment.direccion }}</td>
                                <td>{{ appartment.get_estado_display }}</td>
                                <td><a href="{% url 'details' id=appartment.id %}">Visualizar</a></td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </table>
            </div>
        </div>
        <div id="form_messages">
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </main>
    <footer><a href="{% url 'logout' %}"><button>Log Out</button></a></footer>
</body>
</html>